name: Deploy .NET Core API to AWS

on:
  push:
    branches: [ main ]  # Adjust this if your main branch has a different name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
        
    - name: Build with dotnet
      run: dotnet build --configuration Release
      
    - name: Publish .NET Core Project
      run: dotnet publish -c Release -o dist
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2  # Your AWS region
        
    - name: Deploy to S3
      run: |
        aws s3 sync dist s3://${{ secrets.S3_BUCKET }}/zarichney-api --delete
        
    - name: Update Auto Scaling group
      run: |
        aws autoscaling start-instance-refresh --auto-scaling-group-name zarichney-api-asg
        
    - name: Invalidate CloudFront cache
      run: |
        aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/api/*"